### ISSUE TITLE
Unable to use multiple captchas

### ISSUE THREAD

**Issue by staticdreams** [robiveli/js-captcha#15]
Cannot use multiple captchas on the same page. 
Even if I instantiate them multiple time with ``new jCaptcha()`` and use different class names one of them will come out empty

**Comment by robiveli** [comment]
Good catch, resolved within latest release

**Comment by cristoj** [comment]
Sorry but I can´t make it work with multiple captchas.. I take the example of project and add one more form, and not print the canvas... I tried to add an instance for this new form and not work... I am doing something wrong, but I don't know what....

Another thing, in the documentation you have an old version in the exmaple (canvas/canvasStyle)...
