### ISSUE TITLE
Syntax error in demo source code

### ISSUE THREAD

**Issue by rodrigobdz** [robiveli/js-captcha#2]
There is a syntax error in the **demo source code** that appears in the jPopup on the [jCaptcha](https://www.rvdizajn.com/js-captcha/) website. 

The **closing curly bracket** of the **callback function** is missing.
See the attached screenshot.
![screen shot 2018-05-16 at 16 32 04](https://user-images.githubusercontent.com/14152377/40123554-c4666c40-5926-11e8-8fbd-a762ed60fc6a.png)

The error needs to be fixed in [src/index.html](https://github.com/robiveli/js-captcha/blob/45f586096d4ffad6cc4b4ac6f78a5899b9857bd6/src/index.html#L334) and in [dist/index.html](https://github.com/robiveli/js-captcha/blob/45f586096d4ffad6cc4b4ac6f78a5899b9857bd6/dist/index.html#L276).

**Comment by andchir** [comment]
I think need replace ``setCaptcha(`` to ``setCaptcha.call(this, ``.

**Comment by robiveli** [comment]
@rodrigobdz good catch, fixed!

**Comment by rodrigobdz** [comment]
Could you link the commit that fixed it? @robiveli

**Comment by robiveli** [comment]
@rodrigobdz sure: https://github.com/robiveli/js-captcha/commit/3865da7ffc03c773d57771f449bcc9f39dda158b
