### ISSUE TITLE
How to use it with webpack 4

### ISSUE THREAD

**Issue by AlonsoK28** [robiveli/js-captcha#20]
I am doing this

`import jCaptcha from 'jCaptcha';`

but webpack 4 says

```
ERROR in ./assets/js/mod/lazy-modules/mycaptcha.js
**Module not found**: Error: Can't resolve 'jCaptcha' in '...\assets\js\mod\lazy-modules'
```

I saw in your code that this package was exported using AMD?

**Comment by robiveli** [comment]
You can import it like this:
`import jCaptcha from 'js-captcha';`

**Comment by AlonsoK28** [comment]
Can document this in the README?
