### ISSUE TITLE
jCaptcha definition is completely different to that in the demo!

### ISSUE THREAD

**Issue by stefanuddenberg** [robiveli/js-captcha#22]
I tried getting this to work with the npm package, and the information from the demo is utterly wrong. The demo and the readme specifies that a new jCaptcha should be defined as follows:

```js
new jCaptcha({
    el: ".jCaptcha",
    canvas: {
        class: "jCaptchaCanvas",
        style: {
          // properties for captcha stylings:
          width: 100,
          height: 15,
          textBaseline: "top",
          font: "15px Arial",
          textAlign: "left",
          fillStyle: "#ddd"
        }
    },
...
```
In fact, having looked at the source code and made the code run, the correct API is below:
```js
new jCaptcha({
      el: ".jCaptcha",
      canvasClass: "jCaptchaCanvas",
      canvasStyle: {
        // properties for captcha stylings:
        width: "100px",
        height: "15px",
        textBaseline: "top",
        font: "15px Arial",
        textAlign: "left",
        fillStyle: "#ddd",
      },
...
```

Please update either the API or the docs to correct this issue; thanks!

**Comment by robiveli** [comment]
@stefanuddenberg  Sorry about that, resolved now https://github.com/robiveli/js-captcha/commit/d24aeb1f8b70c4267d7c5fb082d97f3f2f69ab8a
