### ISSUE TITLE
Wich means '*' on captcha operations?

### ISSUE THREAD

**Issue by AlonsoK28** [robiveli/js-captcha#39]
Its posible to remove this `'*'` char from the `js-captcha` ?

Because could be fuzzy for the user.

![image](https://user-images.githubusercontent.com/37458700/168933892-c8518c7b-7e82-4c35-96ef-bc985446eec2.png)

**Comment by bwingenroth** [comment]
The '*' character is the default value set for the requiredValue property. My interpretation is that this is the sensible default that communicates to the user that filling in this field is required. To override that, set:
 requiredValue: ''
 when initializing your new jCaptcha object

**Comment by AlonsoK28** [comment]
![image](https://user-images.githubusercontent.com/37458700/171767431-949fe04a-7726-4fce-ac68-07f00990511a.png)

Thanks for your help 🤖
