### ISSUE TITLE
Display options as markdown table to improve readability

### ISSUE THREAD

**Issue by rodrigobdz** [robiveli/js-captcha#5]
The readability of the [jCaptcha options](https://github.com/robiveli/js-captcha/tree/806edee1d2af8c7a2652d235a3e8d7aa7f42d1a6#options) in the README could be improved.
[Here](https://help.github.com/articles/organizing-information-with-tables/) is a good example of markdown tables.

**Comment by robiveli** [comment]
Done within latest 1.3.0 release
